// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAPeQQJLBT5VrkYf58uuxRDalEZvYmlXg',
    appId: '1:210597436821:web:bde912baaa6edda509ea9c',
    messagingSenderId: '210597436821',
    projectId: 'healthlogger-app39',
    authDomain: 'healthlogger-app39.firebaseapp.com',
    storageBucket: 'healthlogger-app39.appspot.com',
    measurementId: 'G-HSVXX0DPCR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSXk6-PqKIo-guLOF81nJ425VJtFKml-o',
    appId: '1:210597436821:android:ccacf506ae16ecb009ea9c',
    messagingSenderId: '210597436821',
    projectId: 'healthlogger-app39',
    storageBucket: 'healthlogger-app39.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD720pNsfvVJX2Kn45qm3xosD2bIukq924',
    appId: '1:210597436821:ios:eccff9bc6fdd558909ea9c',
    messagingSenderId: '210597436821',
    projectId: 'healthlogger-app39',
    storageBucket: 'healthlogger-app39.appspot.com',
    iosBundleId: 'com.example.healthlogger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD720pNsfvVJX2Kn45qm3xosD2bIukq924',
    appId: '1:210597436821:ios:9c70b5c1f35af63609ea9c',
    messagingSenderId: '210597436821',
    projectId: 'healthlogger-app39',
    storageBucket: 'healthlogger-app39.appspot.com',
    iosBundleId: 'com.example.healthlogger.RunnerTests',
  );
}
